development:
  adapter: postgresql
  encoding: unicode
  database: natural
  pool: 40
  username: natural
  password: natural
test:
  adapter: postgresql
  encoding: unicode
  database: natural_test
  pool: 40
  username: natural
  password: natural
production:
  adapter: postgresql
  encoding: unicode
  database: natural_production
  pool: 40
  username: natural
  password: natural
